config/routes.rb
Rails.application.routes.draw do
  resources :expenses

  resources :time_horizons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/models/time_horizon.rb
class TimeHorizon < ActiveRecord::Base
end

app/models/time_horizons.rb
class TimeHorizons < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:value)
    end
end

app/controllers/time_horizons_controller.rb
class TimeHorizonsController < ApplicationController
  before_action :set_time_horizon, only: [:show, :edit, :update, :destroy]

  # GET /time_horizons
  # GET /time_horizons.json
  def index
    @time_horizons = TimeHorizon.all
  end

  # GET /time_horizons/1
  # GET /time_horizons/1.json
  def show
  end

  # GET /time_horizons/new
  def new
    @time_horizon = TimeHorizon.new
  end

  # GET /time_horizons/1/edit
  def edit
  end

  # POST /time_horizons
  # POST /time_horizons.json
  def create
    @time_horizon = TimeHorizon.new(time_horizon_params)

    respond_to do |format|
      if @time_horizon.save
        format.html { redirect_to @time_horizon, notice: 'Time horizon was successfully created.' }
        format.json { render :show, status: :created, location: @time_horizon }
      else
        format.html { render :new }
        format.json { render json: @time_horizon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_horizons/1
  # PATCH/PUT /time_horizons/1.json
  def update
    respond_to do |format|
      if @time_horizon.update(time_horizon_params)
        format.html { redirect_to @time_horizon, notice: 'Time horizon was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_horizon }
      else
        format.html { render :edit }
        format.json { render json: @time_horizon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_horizons/1
  # DELETE /time_horizons/1.json
  def destroy
    @time_horizon.destroy
    respond_to do |format|
      format.html { redirect_to time_horizons_url, notice: 'Time horizon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_horizon
      @time_horizon = TimeHorizon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_horizon_params
      params.require(:time_horizon).permit(:year_a, :year_b, :year_c, :year_d)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/time_horizons_helper.rb
module TimeHorizonsHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.value %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @expense.value %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tvom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? %></head>
<body>

<%= yield %>

</body>
</html>

app/views/time_horizons/_form.html.erb
<%= form_for(@time_horizon) do |f| %>
  <% if @time_horizon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_horizon.errors.count, "error") %> prohibited this time_horizon from being saved:</h2>

      <ul>
      <% @time_horizon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year_a %><br>
    <%= f.number_field :year_a %>
  </div>
  <div class="field">
    <%= f.label :year_b %><br>
    <%= f.number_field :year_b %>
  </div>
  <div class="field">
    <%= f.label :year_c %><br>
    <%= f.number_field :year_c %>
  </div>
  <div class="field">
    <%= f.label :year_d %><br>
    <%= f.number_field :year_d %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_horizons/edit.html.erb
<h1>Editing time_horizon</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_horizon %> |
<%= link_to 'Back', time_horizons_path %>

app/views/time_horizons/index.html.erb
<h1>Listing time_horizons</h1>

<table>
  <thead>
    <tr>
      <th>Year a</th>
      <th>Year b</th>
      <th>Year c</th>
      <th>Year d</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_horizons.each do |time_horizon| %>
      <tr>
        <td><%= time_horizon.year_a %></td>
        <td><%= time_horizon.year_b %></td>
        <td><%= time_horizon.year_c %></td>
        <td><%= time_horizon.year_d %></td>
        <td><%= link_to 'Show', time_horizon %></td>
        <td><%= link_to 'Edit', edit_time_horizon_path(time_horizon) %></td>
        <td><%= link_to 'Destroy', time_horizon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time horizon', new_time_horizon_path %>

app/views/time_horizons/new.html.erb
<h1>New time_horizon</h1>

<%= render 'form' %>

<%= link_to 'Back', time_horizons_path %>

app/views/time_horizons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year a:</strong>
  <%= @time_horizon.year_a %>
</p>

<p>
  <strong>Year b:</strong>
  <%= @time_horizon.year_b %>
</p>

<p>
  <strong>Year c:</strong>
  <%= @time_horizon.year_c %>
</p>

<p>
  <strong>Year d:</strong>
  <%= @time_horizon.year_d %>
</p>

<%= link_to 'Edit', edit_time_horizon_path(@time_horizon) %> |
<%= link_to 'Back', time_horizons_path %>